language: python

install:
- pip install coreir
- pip install -r requirements.txt
- pip install pytest-cov
- pip install python-coveralls
- pip install -e .

script:
- pytest --cov=peak_gen tests/

after_success:
- coveralls

