import glob
import subprocess
import time

files = glob.glob("smtlib/**_sat**/**.smt2", recursive=True)
# files += glob.glob("smtlib/no-extern-loop_sat_subset/**.smt2", recursive=True)
# files += glob.glob("smtlib/no-extern-loop_unsat_subset/**.smt2", recursive=True)

print(files)

# easy = [f for f in files if "easy" in f]
# medium = [f for f in files if "medium" in f]
# hard = [f for f in files if "hard" in f]

# for f in easy:
#     print(f)
#     start = time.time()
#     subprocess.run(["z3", f])
#     end = time.time()
#     print(end-start)

# for f in medium:
#     print(f)
#     start = time.time()
#     subprocess.run(["z3", f])
#     end = time.time()
#     print(end-start)

# for f in hard:
#     print(f)
#     if "veryhard" not in f:
#         start = time.time()
#         subprocess.run(["z3", f])
#         end = time.time()
#         print(end-start)


line = '''
(set-info :smt-lib-version 2.6)
(set-logic BV)
(set-info :source |
Generated by: Jackson Melchert
Generated on: 2021-3-21
Generator: PEak
Application: Hardware Rewrite Rule Synthesis
Target solver: z3, CVC4
|)
(set-info :license "https://creativecommons.org/licenses/by/4.0/")
(set-info :category "industrial")
(set-info :status sat)
'''

for filename in files:
    with open(filename, 'r+') as f:
        content = f.read()
        f.seek(0, 0)
        f.write(line.rstrip('\r\n') + '\n' + content)